### ISSUE TITLE
Work with Minecraft Server

### ISSUE THREAD

**Issue by brandondrew** [enebo/Purugin#53]
I'm inferring (perhaps incorrectly?) based on [the DMCA takedown](https://github.com/github/dmca/blob/master/2014-09-05-CraftBukkit.md) that this project cannot be used anymore in its current state, unless you happen to have a copy of craftbukkit.jar from before the takedown.

Is it possible to make this work with a vanilla Minecraft server?  (Or is that a ridiculously monumental undertaking?)

**Comment by ryantheleach** [comment]
Making it work with vanilla would be rediculous.

Spigot have a fork of craftbukkit of dubious legal standing, but may get around the DMCA by providing automated tooling to compile the project yourself, they also keep the code as patches from the Mojang code, which *might* prevent them from being subject to the DMCA but as so far it hasn't been challenged in court, and their services are hosted by a host that refuses to take it down from the DMCA request.

That said, I'd like to see a version of this that works with either Forge, or Sponge as that would be the next likely replacements.

**Comment by brandondrew** [comment]
Thanks for the reply!  I expected that to be the case, but thought it was worth asking.  I'm closing this and will open a new issue in line with your suggestions.

**Comment by brandondrew** [comment]
Actually two requests: #54 and #55
