### ISSUE TITLE
Request: compatibility with Sponge (or Forge)

### ISSUE THREAD

**Issue by brandondrew** [enebo/Purugin#55]
Sponge appears to be the future, so it might be worth taking some initial steps toward movement toward compatibility with Sponge.

**Comment by brandondrew** [comment]
Or CanaryMod—that seems to be the best available option at the moment.

**Comment by ryantheleach** [comment]
To my knowledge CanaryMod had entirely died, and someone had forked it recently just trying to get it off the ground. Sponge is alive and kicking, and getting better each release, and have just entered Beta.

**Comment by enebo** [comment]
I have trunk running again with Spigot.  Most everything I tried seemed to be working but I was not all that exhaustive when I was trying out the example plugins.  I am closing this issue since Spigot was the path of least resistance to getting this running again.

**Comment by brandondrew** [comment]
Thanks for the update, and the work getting it working again.
